### ISSUE TITLE
Chapter 02 Nodejs don't understand code

### ISSUE THREAD

**Issue by nguyenhuyhieu261204** [josiahcarlson/redis-in-action#109]
Does anyone understand what the hell this code is?
async function updateToken(client, token, user, item = '') {
  try {
    const timestamp = Utils.currentTimestamp();
    await client.hset('login:', token, user);
    await client.zadd('recent:', timestamp, token);

    if (item) {
      await client.zadd(`viewed:${token}`, timestamp, item);
      await client.zremrangebyrank(`viewed:${token}`, 0, -26);
      await client.zincrby('viewed:', -1, item);
    }
  } catch (err) {
    console.error(err);
  }
}

**Comment by josiahcarlson** [comment]
There are variables `token`, `timestamp`, and `item`.

The first line adds the `item:timestamp` entry to the `"viewed:${token}"` zset.
The second line removes the least-recently used items, forcing `"viewed:${token}"` to only have the 25 newest items.
The last decrements the `"viewed:"` count by 1 for that `item`, for web page analytics in section 2.5 on pages 34-35; if you have the physical copy of the book.
