### ISSUE TITLE
为什么没有PHP版本的代码实现?麻烦大佬考虑一下 谢谢

### ISSUE THREAD

**Issue by 1018103730** [josiahcarlson/redis-in-action#55]
为什么没有PHP版本的代码实现?麻烦大佬考虑一下 谢谢

**Comment by terrencewei** [comment]
请用英语, 而且大佬已经回答了不会出php版

please refer to this: https://github.com/josiahcarlson/redis-in-action/issues/51

**Comment by 1018103730** [comment]
> 请用英语, 而且大佬已经回答了不会出php版
> 
> please refer to this: #51

我找到PHP版本的了~ 谢谢~

**Comment by josiahcarlson** [comment]
Closing because op seems to have found what they are looking for.
