### ISSUE TITLE
I can't find a function named rescale_viewed in Chapter02.java ( Java edition)

### ISSUE THREAD

**Issue by xiaoy9** [josiahcarlson/redis-in-action#65]
def rescale_viewed(conn):
...
  conn.zinterstore('viewed:', {'viewed:' : .5})       //  How to write in Java?
...

**Comment by josiahcarlson** [comment]
The Java examples use the Jedis client. The Jedis client has these options for zunionscore / zinterstore: https://github.com/xetorthio/jedis/blob/master/src/main/java/redis/clients/jedis/commands/Commands.java#L272

I don't use Java, and I am not sure how to even set up an environment to run / test Java, nor am I interested. Other tutorials should provide more information on using Jedis with zinterstore. Sorry I can't help you more.

**Comment by xiaoy9** [comment]
Thank you for a lot.
