### ISSUE TITLE
A bug in Golang code

### ISSUE THREAD

**Issue by Weless** [josiahcarlson/redis-in-action#69]
position: golang/Chapter02/model/client.go  UpdateToken method

line35 `r.Conn.HSet("viewed:"+token, item, timestamp)`
it should be  r.Conn.ZAdd(...)

**Comment by josiahcarlson** [comment]
Thank you for the report, will update soon.

**Comment by josiahcarlson** [comment]
Finally had time to look at and fix, thank you for the bug report.
